"""
Column names in the Population Data-Frame.
"""

SEX = "sex"                                     # common.SexType: SexType.Male for male and SexType.Female for female
AGE = "age"                                     # float: age at the current date
AGE_GROUP = "age_group"                         # int: discrete age grouping based on age
LTP_AGE_GROUP = "ltp_age_group"                 # int: discrete age group for starting / longevity of ltp

RISK = "risk"                                   # float: overall risk value from combined factors
RISK_AGE = "risk_age"                           # float: risk factor based on age
RISK_ADC = "risk_adc"                           # float: risk for AIDS defining condition
RISK_BALANCE = "risk_balance"                   # float: risk factor to re-balance male & female partner numbers
RISK_DIAGNOSIS = "risk_diagnosis"               # float: risk associated with recent HIV diagnosis
RISK_PERSONAL = "risk_personal"                 # float: individual risk reduction applied with a certain probability
RISK_LTP = "risk_long_term_partnered"           # float: risk reduction for people in long term partnerships
RISK_LTP_INFECTED = "risk_ltp_infected"         # float: risk of infection from infected long term partner
RISK_ART_ADHERENCE = "risk_art_adherence"       # float: risk reduction associated with low ART adherence
RISK_INITIAL = "risk_initial"                   # float: initial risk reduction factor
CIRCUMCISED = "circumcised"                     # bool: True if a man is circumcised
CIRCUMCISION_DATE = "circumcision_date"         # None | datetime.date: date of circumcision if circumcised, o/w None
VMMC = "vmmc"                                   # bool: True if voluntary medical male circumcision was applied

NUM_PARTNERS = "num_partners"                   # float: number of short term condomless sex partners during the current time step
LAST_STP_DATE = "last_stp_date"                 # None | datetime.date: date of most recent short-term partnership, o/w None if never partnered (DUMMY)
SEX_MIX_AGE_GROUP = "sex_mix_age_group"         # int: discrete age group for sexual mixing
STP_AGE_GROUPS = "stp_age_groups"               # int array: age groups of short term partners
SEX_BEHAVIOUR = "sex_behaviour"                 # int: sexual behaviour grouping
SEX_BEHAVIOUR_CLASS = "sex_class"               # sexual_behaviour.SexBehaviourClass(enum): Men, Young Women, Older Women, or Sex Workers
LONG_TERM_PARTNER = "long_term_partner"         # bool: True if the subject has a long term condomless partner
LTP_NEW = "ltp_new"                             # bool: True if condomless sex with ltp is new this timestep
LTP_LONGEVITY = "ltp_longevity"                 # int: categorises longevity of long term partnerships (higher => more stable)
LTP_ON_ART = "ltp_on_art"                       # bool: True if an individual's long term partner is on ART (DUMMY)
LTP_MONOGAMOUS = "ltp_monogamous"               # bool: True if a person's long term partner has no short term partners o/w False
LTP_INFECTION_DATE = "ltp_infection_date"       # date: date at which the long term partner gets infected o/w None if not infected
LTP_DIAGNOSED = "ltp_diagnosed"                 # bool: True if a person's long term partner has been diagnosed, o/w False
RECENT_LTP_DIAGNOSED = "recent_ltp_diagnosed"   # bool: True if a person's most recent long term partner was diagnosed
RECENT_LTP_ART = "recent_ltp_art"               # bool: True if a person's most recent long term partner was on ART
LTP_ART = "ltp_art"                             # bool: True if a person's long term partner is on ART
LTP_VIRAL_SUPPRESSED = "ltp_viral_suppressed"   # bool: True if a person's long term partner is virally suppressed
LOW_FERTILITY = "low_fertility"                 # bool: True if a woman is considered to have a 0% chance of pregnancy, o/w False
PREGNANT = "pregnant"                           # bool: True if a woman is currently pregnant
LAST_PREGNANCY_DATE = "last_pregnancy_date"     # None | datetime.date: date of most recent pregnancy, o/w None if never pregnant
BREASTFEEDING = "breastfeeding"                 # bool: True it a woman is breastfeeding (DUMMY)
ANC = "anc"                                     # bool: True if in antenatal care
PMTCT = "pmtct"                                 # bool: True if undergoing prevention of mother to child transmission care
NUM_CHILDREN = "num_children"                   # int: number of children a woman has
NUM_HIV_CHILDREN = "num_HIV_children"           # int: number of children infected with HIV a woman has
WANT_NO_CHILDREN = "want_no_children"           # bool: True if a woman does not want any more children

SEX_WORKER = "sex_worker"                       # bool: True if person is a sex worker, o/w False
SW_AGE_GROUP = "sw_age_group"                   # int: categorises sex worker behaviour by age
DATE_STOP_SW = "date_stop_sex_work"             # date: date at which a former sex worker (last) stopped sex work
SW_PROGRAM_VISIT = "sw_program_visit"           # bool: True if sex worker is engaged with sex worker program
SW_TEST_6MONTHLY = "sw_test_6monthly"           # bool: True if sex worker is tested for HIV bi-annually
SW_HIGHER_INT = "sw_higher_int"                 # bool: TODO: something sex workers and ART disadvantage?
SW_ART_DISENGAGE = "sw_art_disengage"           # bool: True if sex worker has a lower levels of ART engagement
SW_PROGRAM = "sw_program"                       # bool: True if a sex worker program is in place
SW_PROGRAM_EFFECT = "sw_program_effect"         # enum: STRONG or WEAK sex worker program efficacy
EVER_SEX_WORKER = "ever_sex_worker"             # bool: True if person has ever been a sex worker
AGE_STOP_SEX_WORK = "age_stop_sex_work"         # float: age at which former sex worker (last) stopped sex work
LIFE_SEX_RISK = "life_sex_risk"                 # int: value in (1, 2, 3) indicating risk of adopting sex work
STI = "sti"                                     # bool: True if has sexually transmitted infection (non HIV), false o/w (TODO: DUMMIED)

HARD_REACH = "hard_reach"                       # bool: True if person is reluctant to test for HIV (also affects PrEP and VMMC), but will still test if symptomatic or in antenatal care
TEST_MARK = "test_mark"                         # bool: True if a person has been marked for testing this time step
EVER_TESTED = "ever_tested"                     # bool: True if person has ever been tested for HIV
LAST_TEST_DATE = "last_test_date"               # None | datetime.date: date of last HIV test
NSTP_LAST_TEST = "nstp_last_test"               # int: number of short term condomless sex partners since last test (DUMMY)
NP_LAST_TEST = "np_last_test"                   # int: total number of condomless sex partners since last test (DUMMY)
HIV_STATUS = "HIV_status"                       # bool: True if person is HIV positive, o/w False
LTP_STATUS = "LTP_status"                       # bool: True if long term partner is HIV positive, o/w False
RECENT_LTP_STATUS = "recent_LTP_status"         # bool: True if the most recent long term partner was HIV positive
DATE_HIV_INFECTION = "date_HIV_infection"       # None | date: date of HIV infection if HIV+, o/w None
IN_PRIMARY_INFECTION = "in_primary_infection"   # bool: True if a person contracted HIV within 3 months of the current date, o/w False
HIV_INFECTION_GE6M = "HIV_infection_ge6m"       # bool: True is a person has been infected with HIV for 6 months or more (DUMMY)
LTP_IN_PRIMARY = "ltp_in_primary"               # bool: True if a person's long term partner is in primary infection
HIV_DIAGNOSED = "HIV_diagnosed"                 # bool: True if individual had a positive HIV test
HIV_DIAGNOSIS_DATE = "HIV_Diagnosis_Date"       # None | datetime.date: date of HIV diagnosis (to nearest timestep) if HIV+, o/w None
VIRAL_LOAD_GROUP = "viral_load_group"           # int: value 0-5 placing bounds on viral load for an HIV positive person. [(0, 2.7), (2.7, 3.7), (3.7, 4.7), (4.7, 5.7), > 5.7, primary infection]
UNDER_CARE = "under_care"                       # bool: True if under care after a positive HIV diagnosis
VIRAL_LOAD = "viral_load"                       # float: viral load for HIV+ person
MAX_VIRAL_LOAD = "max_viral_load"               # float: maximum viral load for a given time step? (DUMMY)
VIRAL_SUPPRESSION = "viral suppression"         # bool: True if person is virally suppressed
CD4 = "cd4"                                     # None | float: CD4 count per cubic millimeter; set to None for people w/o HIV
CD4_DELTA = "cd4_delta"                         # float: change in CD4 count since the last time step
MAX_CD4 = "max_cd4"                             # float: maximum CD4 count to which a person can return when on ART
CD4_RECOVERY_ON_ART = "cd4_recovery_on_art"     # float: individual propensity for immune recovery given viral suppression
X4_VIRUS = "x4_virus"                           # bool: True if X4 virus is present in person, False otherwise

WHO3_EVENT = "who3_event"                       # bool: True if who3 disease occurs this timestep in HIV positive person
NON_TB_WHO3 = "non_tb_who3"                     # bool: True if non-tb who3 disease occurs this timestep in HIV positive person
TB = "tb"                                       # bool: True if tb occurs this timestep in HIV positive person
TB_DIAGNOSED = "tb_diagnosed"                   # bool: True if TB is diagnosed this timestep
TB_INFECTION_DATE = "tb_infection_date"         # date: Date of start of most recent TB infection
TB_INITIAL_INFECTION = "tb_initial_infection"   # bool: True if TB infection began this timestep
C_MENINGITIS = "c_meningitis"                       # bool: True if cryptococcal meningitis occurs this timestep
C_MENINGITIS_DIAGNOSED = "c_meningitis_diagnosed"   # bool: True if cryptococcal meningitis diagnosed this timestep
SBI = "serious_bacterial_infection"             # bool: True if serious bacterial infection this time step
SBI_DIAGNOSED = "sbi_diagnosed"                 # bool: True if SBI diagnosed this time step
WHO4_OTHER = "who4_other"                       # bool: True if other WHO4 disease occurs this timestep
WHO4_OTHER_DIAGNOSED = "who4_other_diagnosed"   # bool: True if other WHO4 disease diagnosed this timestep
ADC = "AIDS_defining_condition"                 # bool: presence of AIDS defining condition (any WHO4)

R_PREP = "r_prep"                               # float: a semi-permanent random personal variable that determines whether someone is risk informed or suspects they are at risk enough to take PrEP
PREP_ORAL_PREF = "prep_oral_pref"               # float: a value that determines and individual's preference for oral PrEP
PREP_CAB_PREF = "prep_cab_pref"                 # float: a value that determines and individual's preference for injectable Cabotegravir PrEP
PREP_LEN_PREF = "prep_len_pref"                 # float: a value that determines and individual's preference for injectable Lenacapavir PrEP
PREP_VR_PREF = "prep_vr_pref"                   # float: a value that determines and individual's preference for vaginal ring PrEP
PREP_ORAL_RANK = "prep_oral_rank"               # int: an individual's preference ranking for oral PrEP
PREP_CAB_RANK = "prep_cab_rank"                 # int: an individual's preference ranking for injectable Cabotegravir PrEP
PREP_LEN_RANK = "prep_len_rank"                 # int: an individual's preference ranking for injectable Lenacapavir PrEP
PREP_VR_RANK = "prep_vr_rank"                   # int: an individual's preference ranking for vaginal ring PrEP
PREP_ORAL_WILLING = "prep_oral_willing"         # bool: True if an individual is willing to use oral PrEP
PREP_CAB_WILLING = "prep_cab_willing"           # bool: True if an individual is willing to use injectable Cabotegravir PrEP
PREP_LEN_WILLING = "prep_len_willing"           # bool: True if an individual is willing to use injectable Lenacapavir PrEP
PREP_VR_WILLING = "prep_vr_willing"             # bool: True if an individual is willing to use vaginal ring PrEP
PREP_ANY_WILLING = "prep_any_willing"           # bool: True if an individual is willing to use at least one type of PrEP
FAVOURED_PREP_TYPE = "favoured_prep_type"       # prep.PrEPType(enum): PrEP type with highest preference an individual is willing to take that is also currently available, o/w NoPrEP
PREP_ELIGIBLE = "prep_eligible"                 # bool: True if an individual is eligible for PrEP usage
PREP_ORAL_TESTED = "prep_oral_tested"           # bool: True if an individual has tested explicitly to start oral PrEP (DUMMY)
PREP_CAB_TESTED = "prep_cab_tested"             # bool: True if an individual has tested explicitly to start injectable Cab PrEP (DUMMY)
PREP_LEN_TESTED = "prep_len_tested"             # bool: True if an individual has tested explicitly to start injectable Len PrEP (DUMMY)
PREP_VR_TESTED = "prep_vr_tested"               # bool: True if an individual has tested explicitly to start vaginal ring PrEP (DUMMY)
PREP_TYPE = "prep_type"                         # prep.PrEPType(enum): Oral, Cabotegravir, Lenacapavir, or VaginalRing if PrEP is being used, o/w NoPrEP
EVER_PREP = "ever_prep"                         # bool: True if an individual has ever been on PrEP
FIRST_ORAL_START_DATE = "first_oral_start_date"     # None | date: start date of first ever oral PrEP usage
FIRST_CAB_START_DATE = "first_cab_start_date"       # None | date: start date of first ever injectable Cab PrEP usage
FIRST_LEN_START_DATE = "first_len_start_date"       # None | date: start date of first ever injectable Len PrEP usage
FIRST_VR_START_DATE = "first_vr_start_date"         # None | date: start date of first ever vaginal ring PrEP usage
LAST_PREP_START_DATE = "last_prep_start_date"   # None | date: start date of most recent PrEP usage
PREP_JUST_STARTED = "prep_just_started"         # bool: True if PrEP usage began this time step
LAST_PREP_USE_DATE = "last_prep_use_date"       # None | date: most recent date of PrEP usage
LAST_PREP_STOP_DATE = "last_prep_stop_date"     # None | date: stop date of most recent PrEP usage
PREP_PAUSED = "prep_paused"                     # bool: True if PrEP usage is paused this time step due to ineligibility
ON_PREP = "on_prep"                             # bool: True if an individual is currently on PrEP this time step
CONT_ON_PREP = "cont_on_prep"                   # None | timedelta: total length of continuous usage of current PrEP based on user intention (breaks due to ineligibility do not count against continuity - this value will not be reset during an ineligibility break)
CONT_INTENT_ON_PREP = "cont_intent_on_prep"     # None | timedelta: total length of continuous usage of current PrEP based on user intention, including pauses (will continue to increment even during ineligibility breaks)
CONT_ACTIVE_ON_PREP = "cont_active_on_prep"     # None | timedelta: actual total length of continuous usage of current PrEP
CUMULATIVE_PREP_ORAL = "cumulative_prep_oral"   # None | timedelta: total length of cumulative oral PrEP usage
CUMULATIVE_PREP_CAB = "cumulative_prep_cab"     # None | timedelta: total length of cumulative injectable Cab PrEP usage
CUMULATIVE_PREP_LEN = "cumulative_prep_len"     # None | timedelta: total length of cumulative injectable Len PrEP usage
CUMULATIVE_PREP_VR = "cumulative_prep_vr"       # None | timedelta: total length of cumulative injectable vaginal ring PrEP usage

ART_NAIVE = "art_naive"                         # bool: True if person has never been on antiretroviral therapy
ON_ART = "on_art"                               # bool: True if a person is currently on ART
CONT_ON_ART = "cont_on_art"                     # None | timedelta: total length of continuous time on current line of ART
CONT_ON_ARV = "cont_on_arv"                     # None | timedelta: total length of continuous time on antiretroviral drugs (PrEP or ART)
NUM_ACTIVE_DRUGS = "num_active_drugs"           # int: number of active drugs in an individual's regimen
ART_ADHERENCE = "art_adherence"                 # float: percentage of ART intake that is adhered to
RESISTANCE_INDEX = "resistance_index"           # float: an index used to identify an individual's resistance profile for various calculations

ON_ZDV = "on_zdv"                               # ON_X: True if individual is on a particular antiretroviral drug (TODO: all currently DUMMIED)
ON_3TC = "on_3tc"
ON_TEN = "on_ten"
ON_NEV = "on_nev"
ON_DAR = "on_dar"
ON_EFA = "on_efa"
ON_LPR = "on_lpr"
ON_TAZ = "on_taz"
ON_DOL = "on_dol"
ON_CAB = "on_cab"
ON_LEN = "on_len"
ON_OLE = "on_ole"
ON_ISL = "on_isl"

RESISTANCE_MUTATIONS = "resistance_mutations"   # int: total number of resistance mutations in an individual
RTTA_MUTATIONS = "rttams"                       # int: number of RT (reverse transcriptase) gene TA mutations
RT184_MUTATION = "rt184m"                       # bool: True if an individual has the RT gene M184 mutation
RT65_MUTATION = "rt65m"                         # bool: True if an individual has the RT gene K65 mutation
RT151_MUTATION = "rt151m"                       # bool: True if an individual has the RT gene Q151 mutation
RT103_MUTATION = "rt103m"                       # bool: True if an individual has the RT gene K103 mutation
RT181_MUTATION = "rt181m"                       # bool: True if an individual has the RT gene Y181 mutation
RT190_MUTATION = "rt190m"                       # bool: True if an individual has the RT gene G190 mutation
PR32_MUTATION = "pr32m"                         # bool: True if an individual has the PR (protease) gene P32 mutation
PR33_MUTATION = "pr33m"                         # bool: True if an individual has the PR gene P33 mutation
PR46_MUTATION = "pr46m"                         # bool: True if an individual has the PR gene P46 mutation
PR47_MUTATION = "pr47m"                         # bool: True if an individual has the PR gene P47 mutation
PR50L_MUTATION = "pr50lm"                       # bool: True if an individual has the PR gene P50L mutation
PR50V_MUTATION = "pr50vm"                       # bool: True if an individual has the PR gene P50V mutation
PR54_MUTATION = "pr54m"                         # bool: True if an individual has the PR gene P54 mutation
PR76_MUTATION = "pr76m"                         # bool: True if an individual has the PR gene P76 mutation
PR82_MUTATION = "pr82m"                         # bool: True if an individual has the PR gene P82 mutation
PR84_MUTATION = "pr84m"                         # bool: True if an individual has the PR gene P84 mutation
PR88_MUTATION = "pr88m"                         # bool: True if an individual has the PR gene P88 mutation
PR90_MUTATION = "pr90m"                         # bool: True if an individual has the PR gene P90 mutation
IN118_MUTATION = "in118m"                       # bool: True if an individual has the integrase inhibitor IN118 mutation
IN140_MUTATION = "in140m"                       # bool: True if an individual has the integrase inhibitor IN140 mutation
IN148_MUTATION = "in148m"                       # bool: True if an individual has the integrase inhibitor IN148 mutation
IN155_MUTATION = "in155m"                       # bool: True if an individual has the integrase inhibitor IN155 mutation
IN263_MUTATION = "in263m"                       # bool: True if an individual has the integrase inhibitor IN263 mutation
